### ISSUE TITLE
circles in example image seem a bit off

### ISSUE THREAD

**Issue by jedwards1211** [wangzhecheng/DeepSolar#3]
I was looking closely at the example image on your homepage and I noticed a few of the circles showing where solar panels are supposed to be are a bit off.  It's weird, because they aren't false positives -- there are solar panels nearby, the circles just aren't quite in the right place.  Not sure if this image was made by human or computer though.

![image](https://user-images.githubusercontent.com/1448194/50319284-343f3180-048c-11e9-9576-ccd943955b64.png)
![image](https://user-images.githubusercontent.com/1448194/50319293-3c976c80-048c-11e9-9f25-344162f7b402.png)

**Comment by wangzhecheng** [comment]
They are labeled by the computer, but the yellow dots are actually the centers of the image tiles that contain solar panels, instead of the centers of solar panels themselves. 

When a solar panel crosses several image tiles, we merge these tiles and mark the averaging center of these tiles. This may contribute to the location deviations.

**Comment by jedwards1211** [comment]
I see, I was just confused because some of the grayscale images farther down on the page show clearly where it detected solar panels.
